[input]
middle_click_paste = true
client_window_drag = true

[input.mouse]
natural_scroll = false
left_handed = false
accel_profile = "flat"
sensitivity = 0.0
scroll_wheel_step = 60

[input.touchpad]
tap = true
natural_scroll = true
left_handed = false

[input.focus]
follows_mouse = true

[input.keyboard]
repeat_rate = 35
repeat_delay = 300
numlock_toggle = true
track_layout = "global"
layout = "us,fr"
options = "grp:alt_shift_toggle,grp:win_space_toggle"
