$currentRice = default

exec = hyprctl dispatch submap global
submap = global

# Environment variables
source = /home/joran/.config/hypr/default/env.conf

# Execs
source = /home/joran/.config/hypr/default/execs.conf

# Keybinds
bind = Super, R, exec, hyprlauncher
bind = Super, N, exec, swaync-client -t

# Defaults
source = /home/joran/.config/hypr/default/general.conf
source = /home/joran/.config/hypr/default/rules.conf
source = /home/joran/.config/hypr/default/colors.conf
source = /home/joran/.config/hypr/default/keybinds.conf

# nwg-displays
source = /home/joran/.config/hypr/default/workspaces.conf
source = /home/joran/.config/hypr/default/monitors.conf
