$currentRice = default

exec = hyprctl dispatch submap global
submap = global

# Environment variables
source = /home/joran/.config/hypr/Default/env.conf
source = /home/joran/.config/hypr/Default/env.conf

# Compiled rice execs
source = /home/joran/.config/hypr/Default/execs.conf

# Keybinds
bind = Super, R, exec, hyprlauncher
bind = Super, N, exec, swaync-client -t

# Defaults
source = /home/joran/.config/hypr/Default/general.conf
source = /home/joran/.config/hypr/Default/rules.conf
source = /home/joran/.config/hypr/Default/colors.conf
source = /home/joran/.config/hypr/Default/keybinds.conf

# nwg-displays
source = /home/joran/.config/hypr/Default/workspaces.conf
source = /home/joran/.config/hypr/Default/monitors.conf
