$currentRice = default

exec = hyprctl dispatch submap global
submap = global

# Environment variables
source = /home/joran/.config/hypr/default/env.conf

# Execs
source = /home/joran/.config/hypr/default/execs.conf

# Defaults
source = /home/joran/.config/hypr/default/general.conf
source = /home/joran/.config/hypr/default/rules.conf
source = /home/joran/.config/hypr/default/colors.conf
source = /home/joran/.config/hypr/default/keybinds.conf

# nwg-displays
source = /home/joran/.config/hypr/workspaces.conf
source = /home/joran/.config/hypr/monitors.conf

