name = "bar"
position = "top"
height = 20
layer = "background"
"margin.left" = 10
"margin.right" = 10
"margin.top" = 5

[[start]]
type = "menu"
label = "󱓞"

[[start]]
type = "custom"

  [[start.bar]]
  type = "label"
  label = " 󰿟 "
  class = "divider"

[[start]]
type = "workspaces"

[[center]]
type = "focused"
icon_size = 14
truncate = "end"

[[end]]
type = "tray"

[[end]]
type = "volume"
format = "{icon}  {percentage}%"
max_volume = 100

  [end.icons]
  muted = ""
  volume_low = ""
  volume_medium = ""
  volume_high = ""

[[end]]
type = "custom"

  [[end.bar]]
  type = "label"
  label = " 󰿟 "
  class = "divider"

[[end]]
type = "clock"
format = "%H:%M"

  [[end.bar]]
  type = "label"
  label = " 󰿟 "
  class = "divider"

[[end]]
type = "keyboard"
show_scroll = false

[end.icons]
caps_on = "󰪛"

[end.icons.layout_map]
"English (US)" = "English"
"French" = "Fr"

[[end]]
type = "notifications"

[[end]]
type = "custom"
  [[end.bar]]
  type = "button"
  label = ''
  name = 'power-btn'
  on_click = '!wlogout'
