preload = ~/Pictures/TEST Initial-D-AE86-vs-FD3S-Manga-Wallpaper-initiald_upscayl_2560px_high-fidelity-4x.png
wallpaper = ,~/Pictures/TEST Initial-D-AE86-vs-FD3S-Manga-Wallpaper-initiald_upscayl_2560px_high-fidelity-4x.png
