# Environment variables
source = ~/.local/share/rices/default/hypr/env.conf

# Execs
source = ~/.local/share/rices/default/hypr/execs.conf

# Defaults
source = ~/.local/share/rices/default/hypr/general.conf
source = ~/.local/share/rices/default/hypr/rules.conf
source = ~/.local/share/rices/default/hypr/colors.conf
source = ~/.local/share/rices/default/hypr/keybinds.conf
