# ######## Window rules

# Floating dialogs
windowrule = match:title ^(Open File)(.*)$, float on
windowrule = match:title ^(Open File)(.*)$, center on
windowrule = match:title ^(Select a File)(.*)$, float on
windowrule = match:title ^(Select a File)(.*)$, center on
windowrule = match:title ^(Open Folder)(.*)$, float on
windowrule = match:title ^(Open Folder)(.*)$, center on
windowrule = match:title ^(Save As)(.*)$, float on
windowrule = match:title ^(Save As)(.*)$, center on
windowrule = match:title ^(File Upload)(.*)$, float on
windowrule = match:title ^(File Upload)(.*)$, center on
windowrule = match:title ^(.*)(wants to save)$, float on
windowrule = match:title ^(.*)(wants to save)$, center on
windowrule = match:title ^(.*)(wants to open)$, float on
windowrule = match:title ^(.*)(wants to open)$, center on

windowrule = match:class kitty-btop, float on
windowrule = match:class kitty-btop, size 900 600
windowrule = match:class kitty-btop, center on
windowrule = match:class kitty-btop, dim_around on

# Utility windows
windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(pavucontrol)$, center on
windowrule = match:class ^(pavucontrol)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(nm-connection-editor)$, center on
windowrule = match:class ^(nm-connection-editor)$, size (monitor_w*.45) (monitor_h*.45)
windowrule = match:class ^(blueberry.py)$, float on
windowrule = match:class ^(guifetch)$, float on

# Picture-in-Picture
windowrule = match:title ^(\[Pp]icture\[-\s]?\[Ii]n\[-\s]?\[Pp]icture)(.*)$, float on
windowrule = match:title ^(\[Pp]icture\[-\s]?\[Ii]n\[-\s]?\[Pp]icture)(.*)$, pin on
windowrule = match:title ^(\[Pp]icture\[-\s]?\[Ii]n\[-\s]?\[Pp]icture)(.*)$, keep_aspect_ratio on
windowrule = match:title ^(\[Pp]icture\[-\s]?\[Ii]n\[-\s]?\[Pp]icture)(.*)$, size (monitor_w*.25) (monitor_h*.25)
windowrule = match:title ^(\[Pp]icture\[-\s]?\[Ii]n\[-\s]?\[Pp]icture)(.*)$, move (monitor_w*.73) (monitor_h*.72)

# Tiling
windowrule = match:class ^dev.warp.Warp$, tile on

# Tearing (games)
windowrule = match:title .*.exe, immediate on
windowrule = match:title .*minecraft.*, immediate on
windowrule = match:class ^(steam_app).*, immediate on

# JetBrains IDE fix
windowrule = match:class ^jetbrains-.*$, match:float 1, match:title ^$|^\s$|^win\d+$, no_initial_focus on

# ######## Workspace rules
workspace = special:special, gapsout:30

# ######## Layer rules

# Waybar
layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0.2

# Wlogout
layerrule = match:namespace logout_dialog, blur on
layerrule = match:namespace logout_dialog, ignore_alpha 0.2

# SwayNC
layerrule = match:namespace swaync-control-center, animation slide right
layerrule = match:namespace swaync-control-center, blur on,
layerrule = match:namespace swaync-control-center, ignore_alpha 0.2

# Rofi
layerrule = match:namespace rofi, blur on,
layerrule = match:namespace rofi, ignore_alpha 0.2
