# Rice-independent keybinds
bind = Alt, R, exec, fish -c rice-switcher
bind = Super, SUPER_L, exec, pkill rofi || rofi -show drun
bind = Super, T, exec, alacritty
bind = Super, E, exec, dolphin
bind = Super, B, exec, firefox
