# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

input {
    kb_layout = us, fr
    kb_options = grp:win_space_toggle, grp:alt_shift_toggle # this is for changing the layout with Win+Space and Alt+Shift

	touchpad {
       	disable_while_typing = false
        natural_scroll = true
    }
    
    numlock_by_default = true
    accel_profile = flat
    natural_scroll = false
}

exec-once = xrandr --output DP-1 --primary
xwayland {
    force_zero_scaling = true
}
windowrule {
    name = steam-games-monitor
    match:class = ^(steam_app_.*)$
    monitor = DP-1
}
