# Environment variables
source = ~/.local/share/rices/default-ashell/hypr/env.conf

# Execs
source = ~/.local/share/rices/default-ashell/hypr/execs.conf

# Defaults
source = ~/.local/share/rices/default-ashell/hypr/general.conf
source = ~/.local/share/rices/default-ashell/hypr/rules.conf
source = ~/.local/share/rices/default-ashell/hypr/colors.conf
source = ~/.local/share/rices/default-ashell/hypr/keybinds.conf
