[symlinks]
"hypr/hypridle.conf" = "~/.config/hypr/hypridle.conf"
"hypr/hyprlock.conf" = "~/.config/hypr/hyprlock.conf"

"rofi" = "~/.config/rofi"
"yazi" = "~/.config/yazi"
"kitty" = "~/.config/kitty"
