[metadata]
author = "Kanapech"
description = "Default rice"
version = "1.0.0"

[scripts]
start = "scripts/executable_start.sh"
stop = "scripts/executable_stop.sh"

[symlinks]
"hypr/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"

[inherit]
base = "base"
