[metadata]
author = "Kanapech"
description = "Default rice (Waybar, SwayNC, Wlogout)"
version = "1.0.0"

[inherit]
base = "base"

[scripts]
start = "scripts/start.sh"
stop = "scripts/stop.sh"

[symlinks]
"hypr/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"
"swaync" = "~/.config/swaync"
"wlogout" = "~/.config/wlogout"
"waybar" = "~/.config/waybar"

[validate]
lua = "luac -p hypr/*.lua"
